### ISSUE TITLE
Compile error with Go 1.10

### ISSUE THREAD

**Issue by petrkr** [expanse-org/go-expanse#34]
Can not compile with Go version 1.10 as it says I have old version and need atleast 1.7 (but I think 1.10 is newer than 1.7).

Actually if I will change 'if' in build/ci.go to something match my version, compilation is success. But I think this should be solved somehow other proper way and commited to GIT.

#### System information

Go Version: go version go1.10.2 linux/amd64
OS & Version: Arch Linux
Commit hash : 8e6f4610c

````
$ make
build/env.sh go run build/ci.go install ./cmd/gexp
ci.go:180: You have Go version go1.10.2
ci.go:181: go-expanse requires at least Go version 1.7 and cannot
ci.go:182: be compiled with an earlier version. Please upgrade your Go installation.
exit status 1
make: *** [Makefile:15: gexp] Error 1
````

Regards
Petr

**Comment by Quadstank** [comment]
Agree. Just ran into the same issue.

**Comment by chrisfranko** [comment]
v1.8x compiles with go1.10
